## DinD service is required for Testcontainers
#services:
#  - docker:dind
#
#variables:
#  # Instruct Testcontainers to use the daemon of DinD.
#  DOCKER_HOST: "tcp://docker:2375"
#  # Improve performance with overlayfs.
#  DOCKER_DRIVER: overlay2

before_script:
  - apk add docker

build:
  image: adoptopenjdk/openjdk11:jdk-11.0.3_7-alpine
  stage: build
  script:
    - ./gradlew clean build integrationTest
  artifacts:
    reports:
      junit:
        - build/test-results/test/TEST-*.xml
        - build/test-results/integrationTest/TEST-*.xml
