# DinD service is required for Testcontainers
services:
  - docker:dind

variables:
  # Instruct Testcontainers to use the daemon of DinD.
  DOCKER_HOST: "tcp://docker:2375"
  # Improve performance with overlayfs.
  DOCKER_DRIVER: overlay2

build:
  image: openjdk:8-jdk
  retry: 2
  stage: build
  script:
    - export GRADLE_USER_HOME=`pwd`/.gradle
    - ./gradlew clean integrationTest --stacktrace
  cache:
    key: ${CI_COMMIT_REF_SLUG}
    paths:
      - .gradle/
  artifacts:
    paths:
      - build/libs/*.jar
    expire_in: 1 week
    reports:
      junit: build/test-results/test/TEST-*.xml