# DinD service is required for Testcontainers
services:
  - docker:dind

variables:
  # Instruct Testcontainers to use the daemon of DinD.
  DOCKER_HOST: "tcp://docker:2375"
  # Improve performance with overlayfs.
  DOCKER_DRIVER: overlay2

before_script:
  - apk add docker
#   - touch /root/.docker/config.json

build:
  image: openjdk:11-jdk-alpine
  stage: build
  script:
    - ./gradlew clean build integrationTest
  artifacts:
    # paths:
    #   - build/libs/*.jar
    # expire_in: 1 week
    reports:
      junit:
        - build/test-results/test/TEST-*.xml
        - build/test-results/integrationTest/TEST-*.xml
